In [3]:
import numpy as np
# 간단한 행렬 곱 구하는 방법
X = np.random.rand(2)
W = np.random.rand(2,3)
B = np.random.rand(3)

print(X.shape)
print(W.shape)
print(B.shape)

Y = np.dot(X, W) + B
print(Y)

(2,)
(2, 3)
(3,)
[0.52222876 0.65167925 0.55272039]


In [4]:
# 배치 단위 연산 시 편향 계산 예시
X_dot_W = np.array([[0,0,0], [10,10,10]])
B = np.array([1,2,3])

print(X_dot_W)
print(X_dot_W+B)

[[ 0  0  0]
 [10 10 10]]
[[ 1  2  3]
 [11 12 13]]


In [5]:
dY = np.array([[1,2,3],[4,5,6]])
print(dY)

[[1 2 3]
 [4 5 6]]


In [8]:
dB = np.sum(dY, axis=0)
print(dB)

[5 7 9]


In [9]:
class Affine:
  def __init__(self, W, b):
    self.W = W
    self.b = b
    self.x = None
    self.dW = None
    self.db = None

  def forward(self, x):
    self.x = x
    out = np.dot(x, self.W)+self.b
    return out

  def backward(self, dout):
    dx = np.dot(dout, self.W.T)
    self.dW = np.dot(self.x.T, dout)
    self.db = np.sum(dout, axis=0)
    return dx