In [2]:
import numpy as np

편향과 활성화 함수 없이 가중치만 갖는 신경망 예시

In [3]:
X = np.array([1,2])
X.shape

(2,)

In [6]:
W = np.array([[1,3,5],[2,4,6]])
W.shape

(2, 3)

In [7]:
print(W)

[[1 3 5]
 [2 4 6]]


In [8]:
Y = np.dot(X,W)

In [9]:
print(Y)

[ 5 11 17]
