In [1]:
import numpy as np

1차원 행렬

In [2]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

2차원 행렬

In [6]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [8]:
B.shape

(3, 2)

2x2 행렬간의 곱

In [13]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [14]:
B = np.array([[5,6],[7,8]]) 
B.shape

(2, 2)

In [15]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [16]:
# 행렬 곱 연산은 np.dot(A,B)로 ㅇㅇ

2x3 행렬과 3x2 행렬 곱

In [17]:
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [18]:
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [19]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

2x3 행렬과 2x2 행렬의 곱 // 크기가 맞지 않기 때문에 오류가 발생한다

In [20]:
C = np.array([[1,2],[3,4]])
C.shape

(2, 2)

In [21]:
A.shape

(2, 3)

In [22]:
np.dot(A,C)

ValueError: ignored

In [23]:
## 참고로 두 행렬의 순서를 바꿔서 CxA를 할 경우 크기가 맞기 때문에 오류가 발생하지 않는다.
np.dot(C,A)

array([[ 9, 12, 15],
       [19, 26, 33]])

3x2 행렬과 2x1 행렬의 곱

In [24]:
A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

In [25]:
B = np.array([7,8])
B.shape

(2,)

In [26]:
np.dot(A,B)

array([23, 53, 83])