In [ ]:
def step_function1(x):
  if x>0:
    return 1
  else:
    return 0

In [ ]:
def step_function(x):
  y = x > 0
  return y.astype(np.int)

In [ ]:
import numpy as np

In [ ]:
x = np.array([-1.0, 1.0, 2.0])

In [ ]:
x

array([-1.,  1.,  2.])

In [ ]:
y = x>0

In [ ]:
y

array([False,  True,  True])

In [ ]:
step_function(x)

array([0, 1, 1])

In [ ]:
y.astype(np.int)

array([0, 1, 1])